version: '3.6'

services:
  db:
    image: postgres:latest
    container_name: postgres_flats
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d



volumes:
  psql_data: